### PR TITLE
Add Support for \Illuminate\Http\File

### LINKED ISSUE #24: Don't tie in to UploadedFile
This is  a **feature request**.

### Prerequisites
yes

### Description

To enhance code-reuse, and allow programmatically adding (generated) documents, don't limit the class to an Uploadedfile, but just a File.

### Use-case

a certain documentable model let's the server generate a file under certain conditions. For consistency this file should be added to the Documentable of the model.

current workaround is abusing UploadedFile's test mode

### PR DESCRIPTION
**Pull request by jlsjonas**
Closes #24

### CODE REVIEW

**Comment by aocneanu** [comment]
@jlsjonas I guess it would be cleaner if we had an `attach` method for this case besides `upload`. The code would be cleaner and the `attach` / `upload` would be specialised. Only the `file` method would have to accept both types.

What are your thoughts on this?

**Comment by jlsjonas** [comment]
The code would remain mostly the same but the Contract should be cleaner indeed.

You'd still want to optimize etc. in both cases so the PR'd `upload` method should (to remain DRY) be converted in a private method that gets called by new public `upload(UploadedFile $file)` & `attach(File $file)` methods.

This private method would still accept both types, but the public method names would remain closer to their purpose.

Any suggestions on the name of the private method? Then I'll update the PR.

**Comment by aocneanu** [comment]
I guess there's more to it. We could drop the file() method (breaking change), pass the file directly to the upload, attach methods and (re)use a setter for the `isImage` flag.

We can extract the validation logic in two validator classes for the two types of files. Each will handle the specific methods, throw appropriate errors. Both validators could implement a contract. We would call the needed validator a single `validate()` method. upload / attach beside setting the isImage flag could set a `validator` property and then call `validate()`/`processImage()`.

This could be part of the BE refactor that will bring more breaking changes anyway.

**Comment by jlsjonas** [comment]
> upload / attach beside setting the isImage flag

How would you handle this flag?
Potentially expose this as an optional parameter to allow treating an image as file for certain edge-cases

**Comment by aocneanu** [comment]
Extract the logic in a ‘setFileType’, maybe in the future we will have flags for other types

**Comment by jlsjonas** [comment]
[**@aocneanu**](https://github.com/aocneanu) commented on [May 10, 2019, 10:58 AM GMT+2](https://github.com/laravel-enso/FileManager/pull/25#issuecomment-491215269 "2019-05-10T08:58:23Z - Replied by Github Reply Comments"):
> This could be part of the BE refactor that will bring more breaking changes anyway.

To clarify: I assume this means you'll be picking this up?

**Comment by aocneanu** [comment]
I'm on it

**Comment by aocneanu** [comment]
implemented in v3.1

**Pull request closed without merging**
